spring:
  cloud:
    gateway:
      routes:
        - id: handoff-service
          uri: 'http://handoff-service:8085'
          predicates:
            - Path=/api/handoff/**
          filters:
            - StripPrefix=2
        - id: practitioner-service
          uri: 'http://practitioner-service:8081'
          predicates:
            - Path=/api/practitioner/**
          filters:
            - StripPrefix=1
        - id: site-service
          uri: 'http://site-service:8082'
          predicates:
            - Path=/api/sites/**
          filters:
            - StripPrefix=1
        - id: role-service
          uri: 'http://role-service:8083'
          predicates:
            - Path=/api/roles/**
          filters:
            - StripPrefix=1
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
            allowedHeaders: "*"
