spring:
  cloud:
    gateway:
      routes:
        - id: practitioner-service
          uri: 'http://localhost:8081'
          predicates:
            - Path=/api/practitioner/**
          filters:
            - StripPrefix=1
        - id: site-service
          uri: 'http://localhost:8083'
          predicates:
            - Path=/api/sites/**
          filters:
            - StripPrefix=1

        - id: role-service
          uri: 'http://localhost:8082'
          predicates:
            - Path=/api/roles/**
          filters:
            - StripPrefix=1

        - id: practitioner-service-docs
          uri: 'http://localhost:8081'
          predicates:
            - Path=/docs/practitioner-service/**
          filters:
            - RewritePath=/docs/practitioner-service/(?<segment>), /$\{segment}  #NB swagger deploys at app root

        - id: site-service-docs
          uri: 'http://localhost:8083'
          predicates:
            - Path=/docs/site-service/**
          filters:
            - RewritePath=/docs/site-service/(?<segment>), /$\{segment}

        - id: role-service-docs
          uri: 'http://localhost:8082'
          predicates:
            - Path=/docs/role-service/**
          filters:
            - RewritePath=/docs/role-service/(?<segment>), /$\{segment}


      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
            allowedHeaders: "*"
