spring:
  cloud:
    gateway:
      routes:
        - id: practitioner-service
          uri: 'http://localhost:8081'
          predicates:
            - Path=/api/practitioner/**
          filters:
            - StripPrefix=1
        - id: site-service
          uri: 'http://localhost:8083'
          predicates:
            - Path=/api/sites/**
          filters:
            - StripPrefix=1

        - id: role-service
          uri: 'http://localhost:8082'
          predicates:
            - Path=/api/roles/**
          filters:
            - StripPrefix=1

        - id: role-service-docs
          uri: 'http://localhost:8082'
          predicates:
            - Path=/docs/roles/**
          filters:
            - RewritePath=/docs/roles/(?<segment>), /$\{segment}  # Workaround for the limitation of swagger ui springfox that it can only be deployed at app root


      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
            allowedHeaders: "*"
