application:
  message: '"My app settings value here"'
azure:
  keyvault:
    enabled: false
    uri: https://ityekv.vault.azure.net/

spring:
    main:
      allow-bean-definition-overriding: true

init-service:
  identity: <init-service-identity>
