version: "3"
services:
  #################
  # CORE SERVICES #
  #################
  practitioner-service:
    build:
      context: .
      dockerfile: practitioner-service/Dockerfile
      args:
        SVC: practitioner-service
    image: ghcr.io/ndph-arts/practitioner-service:${GITHUB_SHA}
    restart: on-failure
    depends_on:
      - fhir-api
      - role-service
      - site-service
    environment:
      SERVER_PORT: "8081"
      SPRING_PROFILES_ACTIVE: ${PROFILE:-local}
      FHIR_URI: "http://fhir-api:8080"
      ROLE_SERVICE_URI: "http://role-service:8082"
      SITE_SERVICE_URI: "http://site-service:8083"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
      SPRING_CLOUD_CONFIG_LABEL: "main"
      SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
    healthcheck:
      test: curl http://localhost:8081
      interval: 10s
      timeout: 10s
      retries: 12
    ports:
      - "8081:8081"

  role-service:
    build:
      context: .
      dockerfile: role-service/Dockerfile
      args:
        SVC: role-service
    image: ghcr.io/ndph-arts/role-service:${GITHUB_SHA}
    depends_on:
      sql:
        condition: service_healthy
    environment:
      SERVER_PORT: "8082"
      JDBC_DRIVER: com.microsoft.sqlserver.jdbc.SQLServerDriver
      JDBC_URL: jdbc:sqlserver://sql:1433;databaseName=master;user=sa;password=${SAPASSWORD};loginTimeout=15
      SPRING_PROFILES_ACTIVE: ${PROFILE:-local}
    healthcheck:
      test: curl http://localhost:8082
      interval: 10s
      timeout: 10s
      retries: 12
    ports:
      - "8082:8082"

  site-service:
    build:
      context: .
      dockerfile: site-service/Dockerfile
      args:
        SVC: site-service
    image: ghcr.io/ndph-arts/site-service:${GITHUB_SHA}
    depends_on:
      - fhir-api
    environment:
      SERVER_PORT: "8083"
      SPRING_PROFILES_ACTIVE: ${PROFILE:-local}
      FHIR_URI: "http://fhir-api:8080"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
      SPRING_CLOUD_CONFIG_LABEL: "main"
      SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
    healthcheck:
      test: curl http://localhost:8083
      interval: 10s
      timeout: 10s
      retries: 6 # a quick service
    ports:
      - "8083:8083"

  #######################
  # SUPPORTING SERVICES #
  #######################
  init-service:
    # profiles:
    #   - init
    build:
      context: .
      dockerfile: init-service/Dockerfile
      args:
        SVC: init-service
    image: ghcr.io/ndph-arts/init-service:${GITHUB_SHA}
    restart: on-failure
    environment:
      PRACTITIONER_SERVICE: "http://practitioner-service:8081"
      ROLE_SERVICE: "http://role-service:8082"
      SITE_SERVICE: "http://site-service:8083"
      CONFIG_JSON: config.json
      SPRING_PROFILES_ACTIVE: ${PROFILE:-local}
      SPRING_CLOUD_CONFIG_LABEL: "initfix"
    deploy:
      restart_policy:
          condition: none
    depends_on:
      practitioner-service:
        condition: service_healthy
      role-service:
        condition: service_healthy
      site-service:
        condition: service_healthy

  fhir-api:
    image: "mcr.microsoft.com/healthcareapis/r4-fhir-server"
    restart: on-failure
    environment:
      FHIRServer__Security__Enabled: "false"
      SqlServer__ConnectionString: "Server=tcp:sql,1433;Initial Catalog=FHIR;Persist Security Info=False;User ID=sa;Password=${SAPASSWORD};MultipleActiveResultSets=False;Connection Timeout=30;"
      SqlServer__AllowDatabaseCreation: "true"
      SqlServer__SchemaOptions__AutomaticUpdatesEnabled: "true"
      SqlServer__Initialize: "true"
      DataStore: "SqlServer"
    ports:
      - "8080:8080"
    depends_on:
      - sql

  #########################
  # SPRING CLOUD SERVICES #
  #########################
  config-server:
    # profiles:
    #   - springcloud
    build:
      context: .
      dockerfile: config-server/Dockerfile
      args:
        SVC: config-server
    environment:
      SERVER_PORT: "8888"
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "https://github.com/NDPH-ARTS/mts-trial-deployment-config.git"
      SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS: "sample_trial/services, sample_trial/services/*"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
      SPRING_PROFILES_ACTIVE: ${PROFILE:-local}
    image: ghcr.io/ndph-arts/config-server:${GITHUB_SHA}
    restart: on-failure
    ports:
      - "8888:8888"
    healthcheck:
      test: curl http://localhost:8888/
      interval: 10s
      timeout: 10s
      retries: 6 # a quick service

  discovery-server:
    # profiles:
    #   - springcloud
    build:
      context: .
      dockerfile: discovery-server/Dockerfile
      args:
        SVC: discovery-server
    environment:
      EUREKA_CLIENT_REGISTERWITHEUREKA: "false"
      EUREKA_CLIENT_FETCHREGISTRY: "false"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
      SPRING_PROFILES_ACTIVE: ${PROFILE:-local}
    image: ghcr.io/ndph-arts/discovery-server:${GITHUB_SHA}
    restart: on-failure
    ports:
      - "8761:8761"
    healthcheck:
      test: curl http://discovery-server:8761/
      interval: 10s
      timeout: 10s
      retries: 6 # a quick service

  gateway-server:
    build:
      context: .
      dockerfile: gateway-server/Dockerfile
      args:
        SVC: gateway-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
      SPRING_PROFILES_ACTIVE: ${PROFILE:-local}
    image: ghcr.io/ndph-arts/gateway-server:${GITHUB_SHA}
    restart: on-failure
    ports:
      - "8072:8072"
    healthcheck:
      test: curl http://gateway-server:8072/
      interval: 10s
      timeout: 10s
      retries: 6 # a quick service

  #############
  # DATABASES #
  #############

  sql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: ${SAPASSWORD}
      ACCEPT_EULA: "Y"
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd","-U sa -P ${SAPASSWORD} -Q 'SELECT * FROM INFORMATION_SCHEMA.TABLES'" ]
      interval: 10s
      timeout: 10s
      retries: 6
    ports:
      - "1433:1433"
