version: "3"
services:
  #################
  # CORE SERVICES #
  #################
  practitioner-service:
    build:
      context: .
      args:
        SVC: practitioner-service
    image: ghcr.io/ndph-arts/practitioner-service:${GITHUB_SHA}
    restart: on-failure
    depends_on:
      - fhir-api
      - role-service
      - site-service
    environment:
      SERVER_PORT: "8081"
      SPRING_PROFILES_ACTIVE: ${PROFILE:-local}
      FHIR_URI: "http://fhir-api:8099"
      ROLE_SERVICE_URI: "http://role-service:8082"
      SITE_SERVICE_URI: "http://site-service:8083"
      PRACTITIONER_SERVICE_URI: "http://practitioner-service:8081"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
      SPRING_CLOUD_CONFIG_LABEL: "main"
      SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
      # This is the id of the client application
      AZURE_ACTIVEDIRECTORY_CLIENT-ID: ${MTS_AZURE_APP_CLIENT_ID}
      LOGGING_LEVEL_ROOT: ${LOGGING_LEVEL_ROOT:-INFO}
    healthcheck:
      test: curl --fail http://localhost:8081/actuator/health
      interval: 10s
      timeout: 10s
      retries: 12
    ports:
      - "8081:8081"

  role-service:
    build:
      context: .
      args:
        SVC: role-service
    image: ghcr.io/ndph-arts/role-service:${GITHUB_SHA}
    restart: on-failure
    environment:
      SERVER_PORT: "8082"
      JDBC_DRIVER: com.microsoft.sqlserver.jdbc.SQLServerDriver
      JDBC_URL: jdbc:sqlserver://sql:1433;databaseName=master;user=sa;password=${SAPASSWORD};loginTimeout=15
      SPRING_PROFILES_ACTIVE: ${PROFILE:-local}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
      SPRING_CLOUD_CONFIG_LABEL: "main"
      SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
      LOGGING_LEVEL_ROOT: ${LOGGING_LEVEL_ROOT:-INFO}
      ROLE_SERVICE_URI: "http://role-service:8082"
    depends_on:
      - config-server
      - sql
    healthcheck:
      test: curl --fail http://localhost:8082/actuator/health
      interval: 10s
      timeout: 10s
      retries: 12
    ports:
      - "8082:8082"

  site-service:
    build:
      context: .
      args:
        SVC: site-service
    image: ghcr.io/ndph-arts/site-service:${GITHUB_SHA}
    restart: on-failure
    depends_on:
      - fhir-api
    environment:
      SERVER_PORT: "8083"
      SPRING_PROFILES_ACTIVE: ${PROFILE:-local}
      FHIR_URI: "http://fhir-api:8099"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
      SPRING_CLOUD_CONFIG_LABEL: "main"
      SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
      LOGGING_LEVEL_ROOT: ${LOGGING_LEVEL_ROOT:-INFO}
      ROLE_SERVICE_URI: "http://role-service:8082"
    healthcheck:
      test: curl --fail http://localhost:8083/actuator/health
      interval: 10s
      timeout: 10s
      retries: 6 # a quick service
    ports:
      - "8083:8083"

  #######################
  # SUPPORTING SERVICES #
  #######################
  init-service:
    # profiles:
    #   - init
    build:
      context: .
      args:
        SVC: init-service
    image: ghcr.io/ndph-arts/init-service:${GITHUB_SHA}
    restart: "no"
    environment:
      PRACTITIONER_SERVICE_URI: "http://practitioner-service:8081"
      ROLE_SERVICE_URI: "http://role-service:8082"
      SITE_SERVICE_URI: "http://site-service:8083"
      SPRING_PROFILES_ACTIVE: ${PROFILE:-local}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
      SPRING_CLOUD_CONFIG_LABEL: "main"
      SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
      # the following 2 entries allow getting a token to send to other services
      AZURE_CLIENT_ID: ${INIT_AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${INIT_AZURE_CLIENT_SECRET}
      AZURE_TENANT_ID: ${INIT_AZURE_TENANT_ID}
      LOGGING_LEVEL_ROOT: : # always debug
    depends_on:
      - practitioner-service
      - role-service
      - site-service

  fhir-api:
    image: "mcr.microsoft.com/healthcareapis/r4-fhir-server"
    restart: on-failure
    environment:
      FHIRServer__Security__Enabled: "false"
      SqlServer__ConnectionString: "Server=tcp:sql,1433;Initial Catalog=FHIR;Persist Security Info=False;User ID=sa;Password=${SAPASSWORD};MultipleActiveResultSets=False;Connection Timeout=30;"
      SqlServer__AllowDatabaseCreation: "true"
      SqlServer__SchemaOptions__AutomaticUpdatesEnabled: "true"
      SqlServer__Initialize: "true"
      DataStore: "SqlServer"
      ASPNETCORE_URLS: "http://+:8099"
    ports:
      - "8099:8099"
    depends_on:
      - sql
    healthcheck:
      test: busybox wget -O- http://localhost:8099
      interval: 10s
      timeout: 10s
      retries: 12

  #########################
  # SPRING CLOUD SERVICES #
  #########################
  config-server:
    # profiles:
    #   - springcloud
    build:
      context: .
      args:
        SVC: config-server
    environment:
      SERVER_PORT: "8888"
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "https://github.com/NDPH-ARTS/mts-trial-deployment-config.git"
      SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS: "trials/ci-trial/services, trials/ci-trial/services/*"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
      SPRING_PROFILES_ACTIVE: ${PROFILE:-local}
    image: ghcr.io/ndph-arts/config-server:${GITHUB_SHA}
    restart: on-failure
    ports:
      - "8888:8888"
    healthcheck:
      test: curl --fail http://localhost:8888/actuator/health/liveness
      interval: 10s
      timeout: 10s
      retries: 6 # a quick service

  discovery-server:
    # profiles:
    #   - springcloud
    build:
      context: .
      args:
        SVC: discovery-server
    environment:
      SERVER_PORT: "8761"
      EUREKA_CLIENT_REGISTERWITHEUREKA: "false"
      EUREKA_CLIENT_FETCHREGISTRY: "false"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
      SPRING_PROFILES_ACTIVE: ${PROFILE:-local}
    image: ghcr.io/ndph-arts/discovery-server:${GITHUB_SHA}
    restart: on-failure
    ports:
      - "8761:8761"
    healthcheck:
      test: curl --fail http://localhost:8761/actuator/health/liveness
      interval: 10s
      timeout: 10s
      retries: 6 # a quick service

  gateway-server:
    build:
      context: .
      args:
        SVC: gateway-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
      SPRING_PROFILES_ACTIVE: ${PROFILE:-local}
    image: ghcr.io/ndph-arts/gateway-server:${GITHUB_SHA}
    restart: on-failure
    ports:
      - "8080:8080"
    healthcheck:
      test: curl --fail http://localhost:8080/actuator/health
      interval: 10s
      timeout: 10s
      retries: 6 # a quick service

  #############
  # DATABASES #
  #############

  sql:
    image: "mcr.microsoft.com/mssql/server"
    restart: on-failure
    environment:
      SA_PASSWORD: ${SAPASSWORD}
      ACCEPT_EULA: "Y"
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd","-U sa -P ${SAPASSWORD} -Q 'SELECT * FROM INFORMATION_SCHEMA.TABLES'" ]
      interval: 10s
      timeout: 10s
      retries: 6
    ports:
      - "1433:1433"
