version: "3"
services:
  practitioner-service:
    build:
      context: .
      dockerfile: practitioner-service/Dockerfile
      args:
        SVC: practitioner-service
    image: ghcr.io/ndph-arts/practitioner-service:${GITHUB_SHA}
    restart: on-failure
    depends_on:
      - fhir-api
      - config-server
      - role-service
      - site-service
    environment:
      SERVER_PORT: "80"
      SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
      ROLE_SERVICE_URI: "http://role-service:82"
      SITE_SERVICE_URI: "http://site-service:83"
    healthcheck:
      test: curl http://localhost/
      interval: 10s
      timeout: 10s
      retries: 6
    ports:
      - "80:80"

  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
      args:
        SVC: config-server
    environment:
      SERVER_PORT: "8888"
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "https://github.com/NDPH-ARTS/spring-config-server.git"
      SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS: "practitioner-service"
    image: ghcr.io/ndph-arts/config-server:${GITHUB_SHA}
    restart: on-failure
    ports:
      - "8888:8888"
    healthcheck:
      test: curl http://localhost:8888/
      interval: 10s
      timeout: 10s

  site-service:
    build:
      context: .
      dockerfile: site-service/Dockerfile
      args:
        SVC: site-service
    image: ghcr.io/ndph-arts/site-service:${GITHUB_SHA}
    depends_on:
      - fhir-api
    environment:
      SERVER_PORT: "83"
    healthcheck:
      test: curl http://localhost:83
      interval: 10s
      timeout: 10s
      retries: 6
    ports:
      - "83:83"

  fhir-api:
    image: "mcr.microsoft.com/healthcareapis/r4-fhir-server"
    restart: on-failure
    environment:
      FHIRServer__Security__Enabled: "false"
      SqlServer__ConnectionString: "Server=tcp:sql-fhir,1433;Initial Catalog=FHIR;Persist Security Info=False;User ID=sa;Password=${SAPASSWORD};MultipleActiveResultSets=False;Connection Timeout=30;"
      SqlServer__AllowDatabaseCreation: "true"
      SqlServer__SchemaOptions__AutomaticUpdatesEnabled: "true"
      SqlServer__Initialize: "true"
      DataStore: "SqlServer"
    ports:
      - "8080:8080"
    depends_on:
          - sql-fhir

  role-service:
    build:
      context: .
      dockerfile: role-service/Dockerfile
      args:
        SVC: role-service
    image: ghcr.io/ndph-arts/role-service:${GITHUB_SHA}
    depends_on:
      - sql-mts-data
    environment:
      SERVER_PORT: "82"
      JDBC_DRIVER: com.microsoft.sqlserver.jdbc.SQLServerDriver
      JDBC_URL: jdbc:sqlserver://sql-mts-data:1433;databaseName=master;user=sa;password=${SAPASSWORD}
      SPRING_CLOUD_CONFIG_ENABLED: "false"
    healthcheck:
      test: curl http://localhost:82
      interval: 10s
      timeout: 10s
      retries: 12
    ports:
      - "82:82"

  sql-fhir:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: ${SAPASSWORD}
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd","-U sa -P ${SAPASSWORD} -Q 'SELECT * FROM INFORMATION_SCHEMA.TABLES'"]
      interval: 10s
      timeout: 10s
      retries: 6
    ports:
      - "1433:1433"

  sql-mts-data:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: ${SAPASSWORD}
      ACCEPT_EULA: "Y"
    healthcheck:
        test: ["CMD", "/opt/mssql-tools/bin/sqlcmd","-U sa -P ${SAPASSWORD} -Q 'SELECT * FROM INFORMATION_SCHEMA.TABLES'"]
        interval: 10s
        timeout: 10s
        retries: 6
    ports:
      - "1434:1433"

  init-service:
      build:
        context: .
        dockerfile: init-service/Dockerfile
        args:
          SVC: init-service
      image: ghcr.io/ndph-arts/init-service:${GITHUB_SHA}
      restart: on-failure
      environment:
        ROLE_SERVICE: "http://role-service:82"
        SITE_SERVICE: "http://site-service:83"
        PRACTITIONER_SERVICE: "http://practitioner-service:80"
        CONFIG_JSON: config-init-bootstrap-roles.json
      depends_on:
        - practitioner-service
        - role-service
        - site-service
