role:
  service:
    name: role-service
    uri: http://role-service
    endpoint:
      exists: '/roles/{id}'
      paged: '/roles/'
      role: '/roles/{id}'
      roles:
        create: '/roles'
        by:
          ids: 'roles'
      update:
        permissions: '/roles/{id}/permissions'

role-service:
  ribbon:
    listOfServers: ${ROLE_SERVICE_URI:localhost:8082}
