spring:
  main:
    allow-bean-definition-overriding: true

azure:
  activedirectory:
    client-id: <CLIENT_ID>
    session-stateless: true

practitioner:
  service:
    name: practitioner-service
    uri: http://practitioner-service
    endpoint:
      roles: /practitioner/roles

practitioner-service:
  ribbon:
    listOfServers: ${PRACTITIONER_SERVICE_URI:localhost:8081}

site:
  service:
    name: site-service
    uri: http://site-service
    endpoint:
      sites: /sites

site-service:
  ribbon:
    listOfServers: ${SITE_SERVICE_URI:localhost:8083}

init-service:
  identity: <init-service-identity>
