# for local work we specify the uri's manually using env vars
server:
  port: 8083
  error:
    include-message: always
fhir:
  uri: http://localhost:8080
# trial site config - this is the default for local testing, with CCO/REGION/COUNTRY/LCC
site:
  name: Organization
  displayName: site
  type: CCO
  attributes:
    - name: name
      displayName: Name
      validationRegex: '^[a-zA-Z\s]{1,35}$'
    - name: alias
      displayName: Alias
      validationRegex: '^[a-zA-Z\s]{1,35}$'
    - name: parentSiteId
      displayName: Parent Site Id
      validationRegex: ''
    - name: siteType
      displayName: Site Type
      validationRegex: ''
  child:
    - name: Organization
      displayName: site
      type: REGION
      attributes:
        - name: name
          displayName: Name
          validationRegex: '^[a-zA-Z\s]{1,35}$'
        - name: alias
          displayName: Alias
          validationRegex: '^[a-zA-Z\s]{1,35}$'
        - name: parentSiteId
          displayName: Parent Site Id
          validationRegex: ''
        - name: siteType
          displayName: Site Type
          validationRegex: ''
      child:
        - name: Organization
          displayName: site
          type: COUNTRY
          attributes:
            - name: name
              displayName: Name
              validationRegex: '^[a-zA-Z\s]{1,35}$'
            - name: alias
              displayName: Alias
              validationRegex: '^[a-zA-Z\s]{1,35}$'
            - name: parentSiteId
              displayName: Parent Site Id
              validationRegex: ''
            - name: siteType
              displayName: Site Type
              validationRegex: ''
          child:
            - name: Organization
              displayName: site
              type: LCC
              attributes:
                - name: name
                  displayName: Name
                  validationRegex: '^[a-zA-Z\s]{1,35}$'
                - name: alias
                  displayName: Alias
                  validationRegex: '^[a-zA-Z\s]{1,35}$'
                - name: parentSiteId
                  displayName: Parent Site Id
                  validationRegex: ''
                - name: siteType
                  displayName: Site Type
                  validationRegex: ''
