name: Test Pull Request

on: [pull_request, workflow_dispatch]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          export DOCKER_BUILDKIT=1  
          docker build --target export -t test . --output .
      - name: Login to GitHub Container Registry
        if: success()
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_LOGIN }}
      - name: API Test
        run: |
          export DOCKER_BUILDKIT=1
          docker-compose up --abort-on-container-exit
      - name: Publish Unit Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
        with:
          fail_on_test_failures: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: test-reports/TEST*.xml
      - name: Publish Test Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: postman-reports
          path: test-reports/newman-report.html
