server:
  error:
    include-message: always

logging:
  level:
    uk:
      ac:
        ox:
          ndph:
            mts: DEBUG
    org:
      springframework:
        web:
          reactive:
            function:
              client:
                ExchangeFunctions: TRACE

# for local work we specify the uri's manually using env vars
# When Eureka is disabled Ribbon client defaults to a configured server list
role-service:
  uri: http://role-service
  ribbon:
    listOfServers: ${ROLE_SERVICE_URI:localhost:8082}


site-service:
  uri: http://site-service
  ribbon:
    listOfServers: ${SITE_SERVICE_URI:localhost:8083}


practitioner-service:
  uri: http://practitioner-service
  ribbon:
    listOfServers: ${PRACTITIONER_SERVICE_URI:localhost:8081}

---
# for local work we use this static trial config
trial:
  trialName: "My Local Trial"
  persons:
    - givenName: Bootstrap
      familyName: User
      prefix: Mr
      roles:
        - superuser
      userAccount: 5d995fd0-a1ff-4b2c-ba93-238ba9e349b1
  sites:
    - name: CCO
      alias: CCO
      siteType: CCO
  roles:
    - id: superuser
      permissions:
        - id: create-person
        - id: view-person
    - id: country-admin
      permissions:
        - id: create-person
