server:
  error:
    include-message: always

logging:
  level:
    uk:
      ac:
        ox:
          ndph:
            mts: DEBUG
    org:
      springframework:
        web:
          reactive:
            function:
              client:
                ExchangeFunctions: TRACE

auth:
  scope: api://fa5cde1d-d6f8-4d13-9fa4-4d7a374cb290/.default

# for local work we specify the uri's manually using env vars
# When Eureka is disabled Ribbon client defaults to a configured server list
role-service:
  uri: http://role-service
  ribbon:
    listOfServers: ${ROLE_SERVICE_URI:localhost:8082}


site-service:
  uri: http://site-service
  ribbon:
    listOfServers: ${SITE_SERVICE_URI:localhost:8083}


practitioner-service:
  uri: http://practitioner-service
  ribbon:
    listOfServers: ${PRACTITIONER_SERVICE_URI:localhost:8081}

---
# for local work we use this static trial config
mts:
  trial:
    trialName: "My Local Trial"
    persons:
      - givenName: Bootstrap
        familyName: User
        prefix: Mr
        roles:
          - superuser
        userAccount: 5d995fd0-a1ff-4b2c-ba93-238ba9e349b1
      - givenName: automation
        familyName: tester
        prefix: Mr
        roles:
          - superuser
        userAccount: dc32d94e-1ade-4968-b83e-bab949b7e90c
      - givenName: qacreate
        familyName: qaadmin
        prefix: Mr
        roles:
          - admin
        userAccount: d4b73ba8-9d76-408b-b6e1-e3b8953b39e7
    sites:
      - name: CCO
        alias: CCO
        siteType: CCO
        address:
          address1: address1
          address2: address2
          address3: address3
          address4: address4
          address5: address5
          city: city
          country: country
          postcode: postcode
    roles:
      - id: superuser
        permissions:
          - id: create-person
          - id: view-person
          - id: assign-role
          - id: create-site
          - id: link-user
      - id: admin
        permissions:
          - id: create-person
          - id: view-person
      - id: country-admin
        permissions:
          - id: create-person
