name: Docker build and push

on:
  pull_request:
    # branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    name: Build services
    strategy:
      matrix:
        service_name: ["practitioner-service", "trial-config-service", "role-service" ]
    env:
      GHCR: ghcr.io/ndph-arts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build & test
        run: |
          export DOCKER_BUILDKIT=1
          docker build --build-arg SVC="${{ matrix.service_name }}" --target export -t test --output out -f "${{ matrix.service_name }}"/Dockerfile .
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build images
        run: |
          docker-compose build
      - name: Start services using Docker Compose
        timeout-minutes: 5
        run: |
          export SAPASSWORD=$(openssl rand -base64 12)
          export BASE_URL=http://localhost
          ./.ci/docker/check-docker-compose-services.sh
          cd api-tests
          npm run api-test-ci
          cd .. && docker-compose down
          hostname -i | awk '{print $3}'
      - name: Publish Test Report
        if: always()
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: 'api-tests/api-test-results.xml'
          fail_on_test_failures: true
