name: Docker build and push

on:
  pull_request:
    # branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    name: Build services
    strategy:
      matrix:
        service_name: [ "sample-service", "practitioner-service", "site-service" , "trial-config-service" ]
    env:
      GHCR: ghcr.io/ndph-arts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build & test
        run: |
          export DOCKER_BUILDKIT=1
          docker build --build-arg SVC="${{ matrix.service_name }}" --target export -t test --output out -f "${{ matrix.service_name }}"/Dockerfile .
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
        with:
          fail_on_test_failures: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: "**/out/TEST*.xml"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_LOGIN }}
      - name: Build & publish runtime image
        run: |
          docker build --build-arg SVC="${{ matrix.service_name }}" -t $GHCR/"${{ matrix.service_name }}":${{ github.sha }} -f "${{ matrix.service_name }}"/Dockerfile .
          docker push $GHCR/"${{ matrix.service_name }}":${{ github.sha }}
