name: Docker build and push

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          export DOCKER_BUILDKIT=1
          docker build --target export -t test . --output out
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
        with:
          fail_on_test_failures: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: out/TEST*.xml
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_LOGIN }}
      - name: Build and push
        run: |
          docker build -t ghcr.io/ndph-arts/trial-config-service:${{ github.sha }} .
          docker push ghcr.io/ndph-arts/trial-config-service:${{ github.sha }}
